name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+3
  path_provider: ^2.0.11
  path: ^1.8.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/img-1.jpg
    - lib/assets/img-2.jpg
    - lib/assets/img-3.jpg
    - lib/assets/img-4.jpg
    - lib/assets/img-5.jpg
